import 'dart:io';
import 'package:flutter/widgets.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/editor_models.dart';

class AssExportService {
  static Future<bool> exportToAss(Project project) async {
    try {
      final buffer = StringBuffer();
      
      // 1. Script Info Section
      buffer.writeln('[Script Info]');
      buffer.writeln('; Script generated by Typo Edit');
      buffer.writeln('Title: ${project.name} Subtitles');
      buffer.writeln('ScriptType: v4.00+');
      buffer.writeln('WrapStyle: 0');
      buffer.writeln('PlayResX: 1920');
      buffer.writeln('PlayResY: 1080');
      buffer.writeln('ScaledBorderAndShadow: yes');
      buffer.writeln('');
      
      // 2. V4+ Styles Section
      buffer.writeln('[V4+ Styles]');
      buffer.writeln('Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding');
      // Define a default base style
      buffer.writeln('Style: Default,Poppins,50,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1');
      buffer.writeln('');
      
      // 3. Events Section
      buffer.writeln('[Events]');
      buffer.writeln('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text');
      
      // Helper function to format colors from ARGB to ASS BGR format (&HBBGGRR&)
      String toAssColor(int argbColor) {
        final r = (argbColor >> 16) & 0xFF;
        final g = (argbColor >> 8) & 0xFF;
        final b = argbColor & 0xFF;
        final rHex = r.toRadixString(16).padLeft(2, '0').toUpperCase();
        final gHex = g.toRadixString(16).padLeft(2, '0').toUpperCase();
        final bHex = b.toRadixString(16).padLeft(2, '0').toUpperCase();
        return '&H$bHex$gHex$rHex&';
      }
      
      // Helper function to format alpha/transparency from ARGB to ASS transparency (&HAA&)
      String toAssAlpha(int argbColor, double textOpacity) {
        final double opacity = ((argbColor >> 24) & 0xFF) / 255.0 * textOpacity;
        final int transparency = ((1.0 - opacity) * 255.0).clamp(0, 255).toInt();
        final transHex = transparency.toRadixString(16).padLeft(2, '0').toUpperCase();
        return '&H$transHex&';
      }
      
      String toAssTime(Duration duration) {
        final hours = duration.inHours;
        final minutes = duration.inMinutes.remainder(60);
        final seconds = duration.inSeconds.remainder(60);
        final centiseconds = (duration.inMilliseconds.remainder(1000) / 10).floor();
        
        final hStr = hours.toString();
        final mStr = minutes.toString().padLeft(2, '0');
        final sStr = seconds.toString().padLeft(2, '0');
        final cStr = centiseconds.toString().padLeft(2, '0');
        
        return '$hStr:$mStr:$sStr.$cStr';
      }
      
      // Collect and sort all subtitle clips by startTime
      final List<SubtitleClip> clips = [];
      for (var track in project.tracks) {
        for (var clip in track.clips) {
          clips.add(clip);
        }
      }
      clips.sort((a, b) => a.startTime.compareTo(b.startTime));
      
      for (var clip in clips) {
        final startStr = toAssTime(clip.startTime);
        final endStr = toAssTime(clip.endTime);
        
        // Build override tags
        final tags = StringBuffer('{\\an5'); // Center alignment anchor
        
        // Position
        final posX = (clip.x * 1920).toInt();
        final posY = (clip.y * 1080).toInt();
        tags.write('\\pos($posX,$posY)');
        
        // Font name and size
        tags.write('\\fn${clip.fontFamily}');
        tags.write('\\fs${clip.fontSize.toInt()}');
        
        // Text Color and transparency
        tags.write('\\c${toAssColor(clip.color)}');
        tags.write('\\1a${toAssAlpha(clip.color, clip.textOpacity)}');
        
        // Stroke/Outline
        if (clip.isStrokeEnabled && clip.strokeWidth > 0) {
          tags.write('\\bord${clip.strokeWidth.toStringAsFixed(1)}');
          tags.write('\\3c${toAssColor(clip.strokeColor)}');
          tags.write('\\3a${toAssAlpha(clip.strokeColor, 1.0)}');
        } else {
          tags.write('\\bord0');
        }
        
        // Shadow
        if (clip.isShadowEnabled && (clip.shadowOffsetX > 0 || clip.shadowOffsetY > 0)) {
          final depth = ((clip.shadowOffsetX + clip.shadowOffsetY) / 2.0).toStringAsFixed(1);
          tags.write('\\shad$depth');
          tags.write('\\4c${toAssColor(clip.shadowColor)}');
          tags.write('\\4a${toAssAlpha(clip.shadowColor, 1.0)}');
        } else {
          tags.write('\\shad0');
        }
        
        // Rotation
        if (clip.rotation != 0) {
          tags.write('\\z${(-clip.rotation).toStringAsFixed(1)}');
        }
        
        // Scale
        if (clip.scale != 1.0) {
          final scalePct = (clip.scale * 100).toInt();
          tags.write('\\fscx$scalePct\\fscy$scalePct');
        }
        
        // Spacing
        if (clip.letterSpacing != 0) {
          tags.write('\\fsp${clip.letterSpacing.toStringAsFixed(1)}');
        }
        
        // Transitions/Fade animations
        int fadeInMs = 0;
        if (clip.entranceAnimation.type == AnimationType.fadeIn) {
          fadeInMs = clip.entranceAnimation.durationMs;
        }
        int fadeOutMs = 0;
        if (clip.exitAnimation.type == AnimationType.fadeOut) {
          fadeOutMs = clip.exitAnimation.durationMs;
        }
        if (fadeInMs > 0 || fadeOutMs > 0) {
          tags.write('\\fad($fadeInMs,$fadeOutMs)');
        }
        
        tags.write('}');
        
        // Format text (escape newlines if any)
        final formattedText = clip.text.replaceAll('\n', '\\N');
        
        buffer.writeln('Dialogue: 0,$startStr,$endStr,Default,,0,0,0,,$tags$formattedText');
      }
      
      final tempDir = await getTemporaryDirectory();
      final safeName = project.name.replaceAll(RegExp(r'[^\w\s-]'), '_');
      final assFile = File('${tempDir.path}/$safeName.ass');
      await assFile.writeAsString(buffer.toString());
      
      await Share.shareXFiles([XFile(assFile.path)], text: 'Exported ASS Subtitles: ${project.name}');
      return true;
    } catch (e) {
      debugPrint('Error exporting to ASS: $e');
      return false;
    }
  }
}
