import '../../../models/editor_models.dart';
import 'kinetic_style_core.dart';

const fullRandom = KineticStyle(
    name: 'Full Random',
    icon: '🎲',
    colorPalette: [
      0xFFFF0054,
      0xFF00FFFF,
      0xFFF000FF,
      0xFFFFBD00,
      0xFF7000FF,
      0xFF00FF41,
      0xFFFF5400,
      0xFF05D9E8,
      0xFFFE6D73,
      0xFFFFFFFF,
    ],
    fontPool: defaultFonts,
    minFontSize: 26.0,
    maxFontSize: 76.0,
    minScale: 0.7,
    maxScale: 1.8,
    maxRotation: 15.0,
    layoutPreset: LayoutPreset.random,
    entrancePool: [
      AnimationType.fadeIn,
      AnimationType.slideUp,
      AnimationType.scaleUp,
      AnimationType.bounceIn,
      AnimationType.zoomIn,
      AnimationType.elasticDrop,
      AnimationType.glitch,
      AnimationType.flipX,
      AnimationType.throwback,
      AnimationType.spiralDrop,
      AnimationType.elasticStretch,
      AnimationType.flip3D_X,
      AnimationType.spin3D,
    ],
    exitPool: [
      AnimationType.fadeOut,
      AnimationType.slideDown,
      AnimationType.scaleDown,
      AnimationType.zoomOut,
    ],
    animationDurationMs: 400,
    textCase: TextCase.upper,
  );
